arb-dir: lib/localization
output-dir: lib/localization/generated
output-class: L10n
template-arb-file: app_uz.arb
output-localization-file: localization.dart
nullable-getter: false
synthetic-package: false
untranslated-messages-file: lib/localization/generated/untranslated_strings.txt
header: '// ignore_for_file: always_use_package_imports'